_:
    @just -l -u --list-heading $'Welcome to 2021 AoC 🎄\n'

start day:
    #!/usr/bin/env bash
    mkdir -p {{day}}
    touch {{day}}/main.py
    day=$((10#{{day}}))
    # echo "session=53616c74..." > cookie.txt
    curl -b "$(cat cookie.txt)" "https://adventofcode.com/2021/day/$day/input" > {{day}}/input

run day:
    poetry run python {{day}}/main.py

lint:
    poetry run black .
    poetry run flake8 .