_:
    @just -l -u --list-heading $'Welcome to 2021 AoC 🎄\n'

start dir:
    mkdir -p {{dir}}
    touch {{dir}}/main.py
    touch {{dir}}/input

run dir:
    poetry run python {{dir}}/main.py

lint:
    poetry run black .
    poetry run flake8 .