_:
    @just -l -u --list-heading $'Welcome to 2021 AoC 🎄\n'

start dir:
    #!/usr/bin/env bash
    mkdir -p {{dir}}
    touch {{dir}}/main.py
    day=$((10#{{dir}}))
    # echo "session=53616c74..." > cookie.txt
    curl -b "$(cat cookie.txt)" "https://adventofcode.com/2021/day/$day/input" > {{dir}}/input

run dir:
    poetry run python {{dir}}/main.py

lint:
    poetry run black .
    poetry run flake8 .